language: julia

sudo: false

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

after_success:
  - julia -e 'cd(Pkg.dir("WeightedOnlineStats")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
